name: AIMIChallenge
dependencies:
  - python=3.9.7
  - conda=22.9.0
  - pip=21.2.4
  - cudatoolkit=11.3.1
  - pip:
    - pytorch-lightning==1.5.0
    - tensorboard==2.7.0
    - tabulate==0.8.9
    - pillow==8.0.1
    - numpy==1.23.3
    - matplotlib==3.6.1
    - pyyaml==5.3.1
    - tqdm==4.64.1
    - lpips==0.1.4  
    - torch==1.12.1
    - torchvision==0.13.1
    - torchaudio==0.12.1
    - SimpleITK==2.2.0
    - pytorch-msssim==0.2.1