---
# Administration
config_name: "dip_1"

# Data location
path_train: "data/data_train_plus_test_sourceres/dip/"
path_test: "data/data_train_plus_test_sourceres/dip/"

# Hyper params
N: 1
batchsize: 1

# Debugging
verbose: 1

...